version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DOCKER_ENV=1  # Definir variable de entorno para indicar que está corriendo en Docker

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: 'CarinosasAPI_db'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '12345'
