version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: 'CarinosasAPI_db'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '12345'
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: 'CarinosasAPI_db'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '12345'

